name: cold
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  lucide_icons_flutter: ^3.1.13
  supabase_flutter: ^2.0.0
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  video_player: ^2.8.6
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
